#
# Automagically generated by Approximatrix Simply Fortran 2.40
#
FC="C:\Program Files (x86)\Simply Fortran 2\mingw-w64\bin\gfortran.exe"
CC="C:\Program Files (x86)\Simply Fortran 2\mingw-w64\bin\gcc.exe"
AR="C:\Program Files (x86)\Simply Fortran 2\mingw-w64\bin\ar.exe"
WRC="C:\Program Files (x86)\Simply Fortran 2\mingw-w64\bin\windres.exe"
RM=rm -f

IDIR=

LDIR=-LC:/PROGRA~2/SIMPLY~1/MINGW-~1/lib/ 


OPTFLAGS= -g

SPECIALFLAGS=-m32 $(IDIR)

RCFLAGS=-O coff -F pe-i386

PRJ_FFLAGS=

PRJ_CFLAGS=

PRJ_LFLAGS=

FFLAGS=$(SPECIALFLAGS) $(OPTFLAGS) $(PRJ_FFLAGS) -Jmodules 

CFLAGS=$(SPECIALFLAGS) $(OPTFLAGS) $(PRJ_CFLAGS)

"build\MAIN.o": "..\MULTIPLIER\MAIN.f95"
	@echo Compiling ..\MULTIPLIER\MAIN.f95
	@$(FC) -c -o "build\MAIN.o" $(FFLAGS) "..\MULTIPLIER\MAIN.f95"

clean: .SYMBOLIC
	@echo Deleting build\MAIN.o and related files
	@$(RM) "build\MAIN.o"
	@echo Deleting target.exe
	@$(RM) "target.exe"

"target.exe":  "build\MAIN.o" "build\MUL.prj.target"
	@echo Generating target.exe
	@$(FC) -o "target.exe" -static -m32 "build\MAIN.o" $(LDIR) $(PRJ_LFLAGS)

all: "target.exe" .SYMBOLIC

